server:
  port: 443
  domain: "yourdomain.com"
  email: "your@email.com"

health:
  interval: 10s
  timeout: 5s
  path: "/health"

backends:
  - "https://backend1.example.com"
  - "https://backend2.example.com"
  - "https://backend3.example.com"